export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';


export const ADD_CURRENCY_LOADING = "ADD_CURRENCY_LOADING"
export const ADD_CURRENCY = "ADD_CURRENCY"
export const ADD_CURRENCY_ERROR = "ADD_CURRENCY_ERROR"


export const UPDATE_CURRENCY_LOADING = "UPDATE_CURRENCY_LOADING"
export const UPDATE_CURRENCY         = "UPDATE_CURRENCY"
export const UPDATE_CURRENCY_ERROR   = "UPDATE_CURRENCY_ERROR"


export const DELETE_CURRENCY_LOADING = "DELETE_CURRENCY_LOADING"
export const DELETE_CURRENCY = "DELETE_CURRENCY"
export const DELETE_CURRENCY_ERROR = "DELETE_CURRENCY_ERROR"




export const GET_CURRENCY_LOADING = "GET_CURRENCY_LOADING"
export const GET_CURRENCY = "GET_CURRENCY"
export const GET_CURRENCY_ERROR = "GET_CURRENCY_ERROR"

